"""Update User model

Revision ID: 083e34ac99d0
Revises: 5c033383e67f
Create Date: 2020-09-07 19:23:54.480066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '083e34ac99d0'
down_revision = '5c033383e67f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_created', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False))
    op.add_column('user', sa.Column('email', sa.String(length=48), nullable=False))
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_public_user_email'), 'user', ['email'], unique=True, schema='public')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_user_email'), table_name='user', schema='public')
    op.drop_column('user', 'is_verified')
    op.drop_column('user', 'is_admin')
    op.drop_column('user', 'email')
    op.drop_column('user', 'date_created')
    # ### end Alembic commands ###
