"""Add User model

Revision ID: 5c033383e67f
Revises: 8e75b4aaa44a
Create Date: 2020-03-27 01:12:26.445278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c033383e67f'
down_revision = '8e75b4aaa44a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=32), nullable=False),
        sa.Column('password_hash', sa.String(length=77), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint('length(name) >= 3 and length(name) <= 32'),
        sa.CheckConstraint('length(password_hash) = 77'),
        schema='public'
    )
    op.create_index(op.f('ix_public_user_name'), 'user', ['name'], unique=True, schema='public')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_user_name'), table_name='user', schema='public')
    op.drop_table('user', schema='public')
    # ### end Alembic commands ###
