"""Add Light.date_created field

Revision ID: 8e75b4aaa44a
Revises: a92a5e428610
Create Date: 2020-02-28 23:54:11.392759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e75b4aaa44a'
down_revision = 'a92a5e428610'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('light', sa.Column(
        'date_created',
        sa.DateTime(),
        server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
        nullable=False
    ))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('light', 'date_created')
    # ### end Alembic commands ###
